name: Run tests using builded containers
on:
  push:
    branches:
      - main
env:
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: pull pre-built image from docker
        run: |
          docker login -u rmpablo -p ${{secrets.DOCKER_SECRET}}
          docker pull rmpablo/trainee-kafka-consumer_brokers
      - name: run tests
        run: |
          ls /etc/confluent/docker/
          sed -i '/KAFKA_ZOOKEEPER_CONNECT/d' /etc/confluent/docker/configure
          docker run --rm rmpablo/trainee-kafka-consumer_brokers
          npm test