name: Run tests using builded containers
on:
  push:
    branches:
      - main
env:
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Code
        run: |
          npm ci
          npm run build --if-present

      - name: pull pre-built image from docker
        run: |
          docker login -u rmpablo -p ${{secrets.DOCKER_SECRET}}
          docker pull rmpablo/trainee-kafka-consumer_brokers
      - name: run tests
        run: |
          echo $(pwd)
          docker-compose up
          docker run --rm rmpablo/trainee-kafka-consumer_brokers
          npm test
