name: Run tests using builded containers
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: pull pre-built image from docker
        run: |
          docker pull rmpablo/trainee-kafka-consumer_brokers
      - name: run tests
        run: |
          docker run --rm myusername/my_image:latest npm test